language: node_js
node_js:
  - "8"

before_script:
  - echo ROLLBAR_KEY=$ROLLBAR_KEY > .env
  - echo APP_KEY=$APP_KEY >> .env
  - echo APP_SALT=$APP_SALT >> .env
  - make db-setup
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: make lint test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
